<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Dte.FakeWorker</RootNamespace>
    <AssemblyName>Dte.FakeWorker</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.65.0" />
    <PackageReference Include="Grpc.Tools" Version="2.65.0" PrivateAssets="All" />
    <PackageReference Include="Google.Protobuf" Version="3.28.1" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Contracts\dte.proto" GrpcServices="Client" ProtoRoot="..\Contracts" />
  </ItemGroup>

</Project>
